
services:
  openhab:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8101:8101"
    volumes:
      - "/etc/localtime:/etc/localtime:ro" 
      - "/etc/timezone:/etc/timezone:ro"     
      - "./test-config/conf:/openhab/conf"
      - "openhab_userdata:/openhab/userdata"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Berlin"
      CRYPTO_POLICY: unlimited
volumes:
  openhab_userdata:
